version: 0.1

env:
  secrets-manager:
     - aws_access_key:#################
     - aws_secret_key:###########
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipelinejobs --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
